title: "Buttons"
description: |
  Buttons are designed to draw the attention of the user towards purchasing a product.

patterns:
  basic:
    title: "Basic button"
    description: |
      Basic buttons are styled to focus the attention of the user on purchasing actions.
    fields:
      - name: text
        type: string
        example: "Shop now"
      - name: url
        type: url
        example: "/products/"

  ghost:
    title: "Ghost button"
    description: |
      Ghost buttons are used in the navigation bar.

  light:
    title: "Light button"
    description: |
      Light buttons will be used on the form pages, for applying discounts.

  form-submit:
    title: "Form submit button"
    description: |
      Form submit buttons will be used on the form pages, for submitting the form.
