title: "Banners"
description: |
  Banners are designed to provide a visual element that draws the attention of the user. They sometimes serve as a content divider.

patterns:
  call-to-action-banner:
    title: "Call-to-action banner"
    description: |
      Call-to-action banners are used on the homepage of the site to direct users toward the products listed.
    fields:
      - name: heading
        type: string
        example: "The future belongs to those who plan."
      - name: text
        type: string
        example: "Get started today."
      - name: button_text
        type: string
        example: "Shop now"
        required: false
      - name: button_url
        type: url
        example: "/products/"
        required: false

  product-category:
    title: "Product category banner"
    description: |
      Product category banners are clickable banners that lead the user towards various categories of products.
  sale-banner:
    title: Sale banner
    description: |
      The sale banner is intended to attract the viewer's attention. It displays information about an ongoing sale event and has an animated hover state.
    fields:
      - name: heading
        type: string
        example: "Save when you buy multiple planners!"
      - name: text
        type: string
        example: "Valid until May 6, 2019"
      - name: button_text
        type: string
        example: "Save now"
        required: false
      - name: button_url
        type: url
        example: "/promo/"
        required: false
